// Code generated by mockery v2.52.4. DO NOT EDIT.

package migrate

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLegacyResourceMigrator is an autogenerated mock type for the LegacyResourceMigrator type
type MockLegacyResourceMigrator struct {
	mock.Mock
}

type MockLegacyResourceMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLegacyResourceMigrator) EXPECT() *MockLegacyResourceMigrator_Expecter {
	return &MockLegacyResourceMigrator_Expecter{mock: &_m.Mock}
}

// CountLegacyResources provides a mock function with given fields: ctx, excludeNamespace
func (_m *MockLegacyResourceMigrator) CountLegacyResources(ctx context.Context, excludeNamespace string) (int64, error) {
	ret := _m.Called(ctx, excludeNamespace)

	if len(ret) == 0 {
		panic("no return value specified for CountLegacyResources")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, excludeNamespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, excludeNamespace)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, excludeNamespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLegacyResourceMigrator_CountLegacyResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLegacyResources'
type MockLegacyResourceMigrator_CountLegacyResources_Call struct {
	*mock.Call
}

// CountLegacyResources is a helper method to define mock.On call
//   - ctx context.Context
//   - excludeNamespace string
func (_e *MockLegacyResourceMigrator_Expecter) CountLegacyResources(ctx interface{}, excludeNamespace interface{}) *MockLegacyResourceMigrator_CountLegacyResources_Call {
	return &MockLegacyResourceMigrator_CountLegacyResources_Call{Call: _e.mock.On("CountLegacyResources", ctx, excludeNamespace)}
}

func (_c *MockLegacyResourceMigrator_CountLegacyResources_Call) Run(run func(ctx context.Context, excludeNamespace string)) *MockLegacyResourceMigrator_CountLegacyResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLegacyResourceMigrator_CountLegacyResources_Call) Return(_a0 int64, _a1 error) *MockLegacyResourceMigrator_CountLegacyResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLegacyResourceMigrator_CountLegacyResources_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockLegacyResourceMigrator_CountLegacyResources_Call {
	_c.Call.Return(run)
	return _c
}

// MigrateAllToUnified provides a mock function with given fields: ctx, store, excludeNamespace
func (_m *MockLegacyResourceMigrator) MigrateAllToUnified(ctx context.Context, store BulkStoreClient, excludeNamespace string) error {
	ret := _m.Called(ctx, store, excludeNamespace)

	if len(ret) == 0 {
		panic("no return value specified for MigrateAllToUnified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, BulkStoreClient, string) error); ok {
		r0 = rf(ctx, store, excludeNamespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLegacyResourceMigrator_MigrateAllToUnified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrateAllToUnified'
type MockLegacyResourceMigrator_MigrateAllToUnified_Call struct {
	*mock.Call
}

// MigrateAllToUnified is a helper method to define mock.On call
//   - ctx context.Context
//   - store BulkStoreClient
//   - excludeNamespace string
func (_e *MockLegacyResourceMigrator_Expecter) MigrateAllToUnified(ctx interface{}, store interface{}, excludeNamespace interface{}) *MockLegacyResourceMigrator_MigrateAllToUnified_Call {
	return &MockLegacyResourceMigrator_MigrateAllToUnified_Call{Call: _e.mock.On("MigrateAllToUnified", ctx, store, excludeNamespace)}
}

func (_c *MockLegacyResourceMigrator_MigrateAllToUnified_Call) Run(run func(ctx context.Context, store BulkStoreClient, excludeNamespace string)) *MockLegacyResourceMigrator_MigrateAllToUnified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(BulkStoreClient), args[2].(string))
	})
	return _c
}

func (_c *MockLegacyResourceMigrator_MigrateAllToUnified_Call) Return(_a0 error) *MockLegacyResourceMigrator_MigrateAllToUnified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLegacyResourceMigrator_MigrateAllToUnified_Call) RunAndReturn(run func(context.Context, BulkStoreClient, string) error) *MockLegacyResourceMigrator_MigrateAllToUnified_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLegacyResourceMigrator creates a new instance of MockLegacyResourceMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLegacyResourceMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLegacyResourceMigrator {
	mock := &MockLegacyResourceMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
