// Code generated by mockery v2.42.2. DO NOT EDIT.

package query

import (
	context "context"

	backend "github.com/grafana/grafana-plugin-sdk-go/backend"

	dtos "github.com/grafana/grafana/pkg/api/dtos"

	identity "github.com/grafana/grafana/pkg/services/auth/identity"

	mock "github.com/stretchr/testify/mock"
)

// FakeQueryService is an autogenerated mock type for the Service type
type FakeQueryService struct {
	mock.Mock
}

// QueryData provides a mock function with given fields: ctx, user, skipDSCache, reqDTO, applyOptions
func (_m *FakeQueryService) QueryData(ctx context.Context, user identity.Requester, skipDSCache bool, reqDTO dtos.MetricRequest, applyOptions ...func(*QueryDataOption)) (*backend.QueryDataResponse, error) {
	_va := make([]interface{}, len(applyOptions))
	for _i := range applyOptions {
		_va[_i] = applyOptions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, user, skipDSCache, reqDTO)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryData")
	}

	var r0 *backend.QueryDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, identity.Requester, bool, dtos.MetricRequest, ...func(*QueryDataOption)) (*backend.QueryDataResponse, error)); ok {
		return rf(ctx, user, skipDSCache, reqDTO, applyOptions...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, identity.Requester, bool, dtos.MetricRequest, ...func(*QueryDataOption)) *backend.QueryDataResponse); ok {
		r0 = rf(ctx, user, skipDSCache, reqDTO, applyOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.QueryDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, identity.Requester, bool, dtos.MetricRequest, ...func(*QueryDataOption)) error); ok {
		r1 = rf(ctx, user, skipDSCache, reqDTO, applyOptions...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: ctx
func (_m *FakeQueryService) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFakeQueryService creates a new instance of FakeQueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFakeQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FakeQueryService {
	mock := &FakeQueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
